/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ConfigurationsRouteImport } from './routes/configurations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioProductIdRouteImport } from './routes/studio.$productId'
import { Route as AdminDataRouteImport } from './routes/admin.data'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationsRoute = ConfigurationsRouteImport.update({
  id: '/configurations',
  path: '/configurations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioProductIdRoute = StudioProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => StudioRoute,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configurations': typeof ConfigurationsRoute
  '/library': typeof LibraryRoute
  '/studio': typeof StudioRouteWithChildren
  '/admin/data': typeof AdminDataRoute
  '/studio/$productId': typeof StudioProductIdRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configurations': typeof ConfigurationsRoute
  '/library': typeof LibraryRoute
  '/admin/data': typeof AdminDataRoute
  '/studio/$productId': typeof StudioProductIdRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configurations': typeof ConfigurationsRoute
  '/library': typeof LibraryRoute
  '/studio': typeof StudioRouteWithChildren
  '/admin/data': typeof AdminDataRoute
  '/studio/$productId': typeof StudioProductIdRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configurations'
    | '/library'
    | '/studio'
    | '/admin/data'
    | '/studio/$productId'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configurations'
    | '/library'
    | '/admin/data'
    | '/studio/$productId'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/configurations'
    | '/library'
    | '/studio'
    | '/admin/data'
    | '/studio/$productId'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigurationsRoute: typeof ConfigurationsRoute
  LibraryRoute: typeof LibraryRoute
  StudioRoute: typeof StudioRouteWithChildren
  AdminDataRoute: typeof AdminDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurations': {
      id: '/configurations'
      path: '/configurations'
      fullPath: '/configurations'
      preLoaderRoute: typeof ConfigurationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$productId': {
      id: '/studio/$productId'
      path: '/$productId'
      fullPath: '/studio/$productId'
      preLoaderRoute: typeof StudioProductIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioProductIdRoute: typeof StudioProductIdRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioProductIdRoute: StudioProductIdRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigurationsRoute: ConfigurationsRoute,
  LibraryRoute: LibraryRoute,
  StudioRoute: StudioRouteWithChildren,
  AdminDataRoute: AdminDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
